name: CI/CD

on: pull_request

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout/@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: 18.x
      - name: run install, build
        run: | 
          npm install
          npm run build
          npm publish